"""initial schema

Revision ID: 5718ea061dd5
Revises: 
Create Date: 2026-08-28 10:50:38.465465
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '5718ea061dd5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_events_name'), 'analytics_events', ['name'], unique=False)
    op.create_index(op.f('ix_analytics_events_user_id'), 'analytics_events', ['user_id'], unique=False)
    op.create_table('anonymous_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mbti', sa.String(length=4), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anonymous_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['anonymous_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anonymous_sessions_token_hash'), 'anonymous_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_anonymous_sessions_user_id'), 'anonymous_sessions', ['user_id'], unique=False)
    op.create_table('drink_feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('tea_id', sa.String(length=80), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('user_words', sa.Text(), nullable=True),
    sa.Column('normalized_tags', sa.JSON(), nullable=False),
    sa.Column('infusion_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['anonymous_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drink_feedback_tea_id'), 'drink_feedback', ['tea_id'], unique=False)
    op.create_index(op.f('ix_drink_feedback_user_id'), 'drink_feedback', ['user_id'], unique=False)
    op.create_table('passport_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('tea_id', sa.String(length=80), nullable=False),
    sa.Column('saved', sa.Boolean(), nullable=False),
    sa.Column('brewed', sa.Boolean(), nullable=False),
    sa.Column('tasted', sa.Boolean(), nullable=False),
    sa.Column('realm_unlocked', sa.Boolean(), nullable=False),
    sa.Column('favorite_infusion', sa.Integer(), nullable=True),
    sa.Column('user_description', sa.Text(), nullable=True),
    sa.Column('normalized_tags', sa.JSON(), nullable=False),
    sa.Column('first_drunk_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['anonymous_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tea_id', name='uq_passport_user_tea')
    )
    op.create_index(op.f('ix_passport_entries_tea_id'), 'passport_entries', ['tea_id'], unique=False)
    op.create_index(op.f('ix_passport_entries_user_id'), 'passport_entries', ['user_id'], unique=False)
    op.create_table('swipe_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('client_event_id', sa.String(length=80), nullable=False),
    sa.Column('card_id', sa.String(length=40), nullable=False),
    sa.Column('tea_id', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['anonymous_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_event_id', name='uq_swipe_user_client_event')
    )
    op.create_index(op.f('ix_swipe_events_tea_id'), 'swipe_events', ['tea_id'], unique=False)
    op.create_index(op.f('ix_swipe_events_user_id'), 'swipe_events', ['user_id'], unique=False)
    op.create_table('taste_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('absolute_weight', sa.Float(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['anonymous_users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('voice_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('tea_id', sa.String(length=80), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('provider_mode', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('room_id', sa.String(length=80), nullable=True),
    sa.Column('task_id', sa.String(length=80), nullable=True),
    sa.Column('brew_stage', sa.String(length=24), nullable=True),
    sa.Column('infusion_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['anonymous_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_sessions_user_id'), 'voice_sessions', ['user_id'], unique=False)
    op.create_table('voice_turns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('voice_session_id', sa.String(length=36), nullable=False),
    sa.Column('client_turn_id', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['voice_session_id'], ['voice_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voice_session_id', 'client_turn_id', name='uq_voice_turn_client')
    )
    op.create_index(op.f('ix_voice_turns_voice_session_id'), 'voice_turns', ['voice_session_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_turns_voice_session_id'), table_name='voice_turns')
    op.drop_table('voice_turns')
    op.drop_index(op.f('ix_voice_sessions_user_id'), table_name='voice_sessions')
    op.drop_table('voice_sessions')
    op.drop_table('taste_profiles')
    op.drop_index(op.f('ix_swipe_events_user_id'), table_name='swipe_events')
    op.drop_index(op.f('ix_swipe_events_tea_id'), table_name='swipe_events')
    op.drop_table('swipe_events')
    op.drop_index(op.f('ix_passport_entries_user_id'), table_name='passport_entries')
    op.drop_index(op.f('ix_passport_entries_tea_id'), table_name='passport_entries')
    op.drop_table('passport_entries')
    op.drop_index(op.f('ix_drink_feedback_user_id'), table_name='drink_feedback')
    op.drop_index(op.f('ix_drink_feedback_tea_id'), table_name='drink_feedback')
    op.drop_table('drink_feedback')
    op.drop_index(op.f('ix_anonymous_sessions_user_id'), table_name='anonymous_sessions')
    op.drop_index(op.f('ix_anonymous_sessions_token_hash'), table_name='anonymous_sessions')
    op.drop_table('anonymous_sessions')
    op.drop_table('anonymous_users')
    op.drop_index(op.f('ix_analytics_events_user_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_name'), table_name='analytics_events')
    op.drop_table('analytics_events')
    # ### end Alembic commands ###
